# Generated by Django 5.2.1 on 2025-08-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='joined_amount',
            field=models.BigIntegerField(),
        ),
    ]
