# Generated by Django 5.2.1 on 2025-08-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_price_alter_partner_joined_amount'),
        ('core', '0002_iqd_integers'),
    ]

    operations = [
    ]
