# Generated by Django 5.2.1 on 2025-09-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_customer_address_order_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('IN', 'Ingoing'), ('OUT', 'Outgoing')], max_length=3, null=True),
        ),
    ]
